baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'jon112358 study Blog'
theme = "hugo-blog-awesome"

[[params.socialIcons]]
name = "github"
url = "https://github.com/jon1123"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/jonmkuhl/"

[params]
goToTop = true